### ISSUE TITLE
[bug] delete 시 members의 크기가 0보다 커야함

### ISSUE THREAD

**Issue by Eunbi-kwon** [dandyrilla/ddby#1]
https://github.com/dandyrilla/ddby/blob/4ae7a21ea7ad24fe4f1185db46e085f6910817be/run.py#L121
- `n1 = len(members)` 이 0보다 커야 delete 연산이 의미가 있음

**Comment by dandyrilla** [comment]
@Eunbi-kwon 님,
del 기능에서 멤버 리스트의 크기를 확인하도록 조치했습니다.
이슈 등록에 감사드립니다.
