### ISSUE TITLE
[bug] ddby 시 members의 크기가 1보다 커야함

### ISSUE THREAD

**Issue by Eunbi-kwon** [dandyrilla/ddby#2]
https://github.com/dandyrilla/ddby/blob/4ae7a21ea7ad24fe4f1185db46e085f6910817be/run.py#L172
- 한명 이하의 멤버가 있을때는 ddby의 의미가 없으므로, 에러를 반환해야 합니다.
- 한 팀에 할당할 수 있는 maxUserCount를 받으면 더 좋을 것 같슴다

**Comment by dandyrilla** [comment]
@Eunbi-kwon 님,
열정을 가지고 이슈등록을 해주셔서 감사합니다.
ddby를 실행했을 때 현재 멤버 리스트를 확인하도록 했습니다.
확인 부탁드립니다.
