### ISSUE TITLE
[feature] d:lotto 명령어 추가 니즈

### ISSUE THREAD

**Issue by Eunbi-kwon** [dandyrilla/ddby#3]
![image](https://user-images.githubusercontent.com/3636629/36899149-275dfcba-1e61-11e8-9435-58b5150b0a43.png)

- lotto 번호 추천 기능을 추가해주세요

**Comment by dandyrilla** [comment]
@Eunbi-kwon 님,
말씀하신 대로 d:lotto 명령어를 추가했습니다.
d:lotto 5 와 같이 숫자를 추가로 입력하면 5 게임의 로또 번호를 생성해줍니다.
이슈를 등록해주셔서 감사합니다! 확인 부탁드립니다.
